### ISSUE TITLE
Error: Init:CreateContainerError when GCS Fuse CSI driver enabled with GKE Cluster on apache airflow deployment

### ISSUE THREAD

**Issue by Zudhakar** [GoogleCloudPlatform/gcs-fuse-csi-driver#49] opened 2023-07-25 11:25 UTC
# Source
While deploying apache airflow deployment to the GKE cluster which is enabled gcs-fuse-csi-driver for Mount filesystem, getting 
**Init:CreateContainerError.** while describe the pod, we were get error like **Error: failed to reserve container name **"check-db_sample-airflow-db-migrations-5d99cc5b86-bjqd2_sample_c8e8766c-b2e0-486c-8e1a-f2db0fe20745_0": name "check-db_sample-airflow-db-migrations-5d99cc5b86-bjqd2_sample_c8e8766c-b2e0-486c-8e1a-f2db0fe20745_0" is reserved for "5738e4d666b4c6872c316b752cac8633b901218f71b3f63c3176f365e5e86e9e".****

Here I will attach the source code for apache airflow helm chart,
https://github.com/airflow-helm/charts/tree/main/charts/airflow 

I will share the values.yaml for  db-migrations 

    values.yaml
    ########################################
    ## COMPONENT | db-migrations Deployment
    ########################################
    dbMigrations:
    ## if the db-migrations Deployment/Job is created
    ## - [WARNING] if `false`, you have to MANUALLY run `airflow db upgrade` when required
    ##
    enabled: true

    ## if a post-install helm Job should be used (instead of a Deployment)
    ## - [WARNING] setting `true` will NOT work with the helm `--wait` flag,
    ##   this is because post-install helm Jobs run AFTER the main resources become Ready,
    ##   which will cause a deadlock, as other resources require db-migrations to become Ready
    ##
    runAsJob: false

    ## resource requests/limits for the db-migrations Pods
    ## - spec for ResourceRequirements:
    ##   https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#resourcerequirements-v1-core
    ##
    resources: {}

    ## the nodeSelector configs for the db-migrations Pods
    ## - docs for nodeSelector:
    ##   https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#nodeselector
    ##
    nodeSelector: {}

    ## the affinity configs for the db-migrations Pods
    ## - spec for Affinity:
    ##   https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#affinity-v1-core
    ##
    affinity: {}

    ## the toleration configs for the db-migrations Pods
    ## - spec for Toleration:
    ##   https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#toleration-v1-core
    ##
    tolerations: []

    ## the security context for the db-migrations Pods
    ## - spec for PodSecurityContext:
    ##   https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#podsecuritycontext-v1-core
    ##
    securityContext:
      fsGroup: 3003
      runAsGroup: 2002
      runAsUser: 1001

    ## Labels for the db-migrations Deployment
    ##
    labels: {}

    ## Pod labels for the db-migrations Deployment
    ##
    podLabels: {}

    ## annotations for the db-migrations Deployment/Job
    ##
    annotations: {}
    
    ## Pod annotations for the db-migrations Deployment/Job
    ##
    podAnnotations:
      gke-gcsfuse/volumes: "true"

    ## if we add the annotation: "cluster-autoscaler.kubernetes.io/safe-to-evict" = "true"
    ##
    safeToEvict: false

    ## the number of seconds between checks for unapplied db migrations
    ## - only applies if `airflow.dbMigrations.runAsJob` is `false`
    ##
    checkInterval: 300

Persistence Volume and Persistence Volume Claim Configuration with terraform file

     pv_pvc.tf
     resource "kubernetes_persistent_volume" "sample-airflow-logs-pv" {
     metadata {
         name = "sample-airflow-logs-pv"
     }
     spec {
       capacity = {
       storage = "150Gi"
     }
     access_modes = ["ReadWriteMany"]
     storage_class_name = "sample-eks-efs-sc"
     mount_options = [
      "implicit-dirs",
      "uid=1001",
      "gid=3003" ]
     persistent_volume_source {
      csi {
        driver = "gcsfuse.csi.storage.gke.io"
        volume_handle = "sample-airflow-logs-fs"
           } 
         }
       }
     }
    resource "kubernetes_persistent_volume_claim" "sample-airflow-logs-pvc" {
    metadata {
       name      = "sample-airflow-logs"
       namespace = "sample"
    }

     spec {
       access_modes       = ["ReadWriteMany"]
       storage_class_name = "sample-eks-efs-sc"
       volume_name = "sample-airflow-logs-pv"
       resources {
          requests = {
            storage = "150Gi"
         }
       }
     }
     depends_on = [
       kubernetes_persistent_volume.sample-airflow-logs-pv
     ]
    }

# Error:
   Command : kubectl get pods -n dataworkz
   Error:

    sample-airflow-db-migrations-5d99cc5b86-9zsdt   0/2     Init:CreateContainerError   0          71m

    sample-airflow-redis-master-0                   2/2     Running                     0          71m

    sample-airflow-scheduler-7b4c5bcdff-tt246       0/2     Init:CreateContainerError   0          71m

    sample-airflow-sync-users-79d7d4f477-9gzph      0/2     Init:CreateContainerError   0          71m

    sample-airflow-web-57755c9659-9hwh4             0/2     Init:CreateContainerError   0          71m

    sample-airflow-worker-0                         0/2     Init:CreateContainerError   0          71m

   Commnad : kubectl describe pod sample-airflow-db-migrations-5d99cc5b86-bjqd2 -n dataworkz

   Error from Event:
   Events:

    Type     Reason     Age                 From               Message

    ----     ------     ----                ----               -------

    Normal   Scheduled  2m14s               default-scheduler  Successfully assigned dataworkz/sample-airflow-db-migrations-5d99cc5b86-bjqd2 to gke-sample-all-in-on-sample-default-p-4e593424-qtww

    Warning  Failed     13s                 kubelet            Error: context deadline exceeded

    Normal   Pulled     0s (x3 over 2m13s)  kubelet            Container image "[xxxxxxxxxxxxxx.dkr.ecr.us-west-2.amazonaws.com/dataworkz/airflow:2.5.3](http://xxxxxxxxxxxxxxx.dkr.ecr.us-west-2.amazonaws.com/dataworkz/airflow:2.5.3)" already present on machine

    Warning  Failed     0s (x2 over 13s)    kubelet            Error: failed to reserve container name "check-db_sample-airflow-db-migrations-5d99cc5b86-bjqd2_sample_c8e8766c-b2e0-486c-8e1a-f2db0fe20745_0": name "check-db_sample-airflow-db-migrations-5d99cc5b86-bjqd2_sample_c8e8766c-b2e0-486c-8e1a-f2db0fe20745_0" is reserved for "5738e4d666b4c6872c316b752cac8633b901218f71b3f63c3176f365e5e86e9e"

# Observation:

As per the official document for gcs-fuse-csi-driver, we followed below steps
https://cloud.google.com/kubernetes-engine/docs/how-to/persistent-volumes/cloud-storage-fuse-csi-driver

1. Step1: Added pod annotations to the deployment values.yaml 
     podAnnotations:
         gke-gcsfuse/volumes: "true"
         
2. Step2: Added security context to values.yaml
      securityContext:
        fsGroup: 3003
        runAsGroup: 2002
        runAsUser: 1001
        
3. Step3: Tried more pod annotations to the values.yaml
       podAnnotations:
           gke-gcsfuse/volumes: "true"
           gke-gcsfuse/cpu-limit: "2048m"
           gke-gcsfuse/memory-limit: "2048Mi"
           gke-gcsfuse/ephemeral-storage-limit: "50Gi"

we are getting error while creating init container on check db line, below are the init container helm deployment file 

  deployment.yaml
  ```yaml
initContainers:
        {{- if $extraPipPackages }}
        {{- include "airflow.init_container.install_pip_packages" (dict "Release" .Release "Values" .Values "extraPipPackages" $extraPipPackages) | indent 8 }}
        {{- end }}
        {{- if .Values.dags.gitSync.enabled }}
        ## git-sync is included so "airflow plugins" & "python packages" can be stored in the dags repo
        {{- include "airflow.container.git_sync" (dict "Release" .Release "Values" .Values "sync_one_time" "true") | indent 8 }}
        {{- end }}
        {{- include "airflow.init_container.check_db" (dict "Release" .Release "Values" .Values "volumeMounts" $volumeMounts) | indent 8 }}
```

Please refer the below link to get full script of deployment.yaml 
https://github.com/airflow-helm/charts/blob/main/charts/airflow/templates/db-migrations/db-migrations-deployment.yaml

Please guide to add any additional configuration to get work properly.

**Comment by songjiaxun** [comment] 2023-07-26 22:21
Thanks for reporting the issue.

Unfortunately, currently the driver does not support volumes for `initContainers`, see https://github.com/GoogleCloudPlatform/gcs-fuse-csi-driver/issues/38.

**Comment by Zudhakar** [comment] 2023-07-27 11:21
Hi @songjiaxun,

Thanks for addressing this issue.

We are using GKE version 1.26.5-gke, shall we use the same version to leverage as sidecar container that you recommended in #38 or we need to wait for kubernetes version  update v1.28 to use sidecar.

**Comment by songjiaxun** [comment] 2023-07-27 17:17
@Zudhakar I would recommend waiting for the sidecar feature is officially supported in k8s 1.28.

Also I am working on a workaround. It may or may not work for the init containers. Basically, manual injection of the sidecar may work. I will keep you posted with my experiment.

**Comment by Zudhakar** [comment] 2023-07-28 11:33
@songjiaxun 

I just noticed that GKE  version 1.28 release date is 2023-08-15. Can you please confirm that this change will be part of it and available.

Thanks.

**Comment by songjiaxun** [comment] 2023-08-01 23:34
Hi @Zudhakar , the Kubernetes sidecar feature is still alpha, and GKE cannot use the feature until it becomes beta.

We are working on testing the Kubernetes sidecar feature, and will start to use the feature as soon as possible.

**Comment by Zudhakar** [comment] 2023-08-02 11:42
Thanks for the update @songjiaxun 

Is there any approximate time frame?

**Comment by songjiaxun** [comment] 2023-08-07 23:04
@Zudhakar we are working to test the feature now, and we will update with the time frame after the tests.

Closing this item as this is duplicated with https://github.com/GoogleCloudPlatform/gcs-fuse-csi-driver/issues/38. Please keep following up on the issue https://github.com/GoogleCloudPlatform/gcs-fuse-csi-driver/issues/38.

**Closed by songjiaxun** 2023-08-07 23:04 UTC
Labels: enhancement

**Comment by songjiaxun** [comment] 2023-08-07 23:06
Duplicate of #38
